name: Build
on: [pull_request, push]

jobs:
  prepare-matrix:
    runs-on: ubuntu-22.04
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - id: set-matrix
        shell: bash
        run: |
          loaders=$(grep -E '^mod_loaders' gradle.properties | cut -d= -f2)
          loaders=$(echo $loaders)
          json=$(printf '%s\n' $loaders | jq -R . | jq -s -c '{platform: .}')
          echo "matrix=$json" >> $GITHUB_OUTPUT

  build:
    needs: prepare-matrix
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.prepare-matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v2
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: microsoft
      - run: chmod +x ./gradlew
      - name: Build ${{ matrix.platform }}
        run: ./gradlew buildAndCollect+${{ matrix.platform }}+All